version: '3.4'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - forwork_volume:/var/lib/postgresql/data/

volumes:
  forwork_volume:
    driver: local